### ISSUE TITLE
Please tag releases based on versions of the code

### ISSUE THREAD

**Issue by Conan-Kudo** [ebiggers/ntfs-3g-system-compression#2]
I am attempting to package your ntfs-3g plugin, but there doesn't appear to be any tags related to versions of the code released.

For example, https://github.com/ebiggers/ntfs-3g-system-compression/commit/f01c486d2f12c25c6896fc47092497e43cb3e3cb indicates that it is version 0.4 in `configure.ac` file.

Could you please tag releases?

**Comment by ebiggers** [comment]
I went ahead and bumped the version up to v1.0 and tagged that.  I also posted a standard tarball on the releases page (https://github.com/ebiggers/ntfs-3g-system-compression/releases/download/v1.0/ntfs-3g-system-compression-1.0.tar.gz), so you can use that for packaging if it's easier.  Thanks for the interest!

**Comment by ebiggers** [comment]
In case it's helpful, this is what I'm using to package it for Arch Linux:  https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ntfs-3g-system-compression
