### ISSUE TITLE
Related post - OneDrive issue

### ISSUE THREAD

**Issue by ferroao** [ebiggers/ntfs-3g-system-compression#4]
https://askubuntu.com/questions/982742/how-to-read-onedrive-ntfs-folder-in-ubuntu
I have a NTFS external HD. Recently I put in Windows everything inside a folder in it as the OneDrive folder. Mounting the HD in ubuntu, it failed to open the folder. unsupported reparse point in ls -l. I updated the ntfs-3g to the most recent version https://www.tuxera.com/community/open-source-ntfs-3g/, which did'nt work to open the folder. Link to unknown in Nautilus. I installed a plugin https://github.com/ebiggers/ntfs-3g-system-compression that here https://bugzilla.redhat.com/show_bug.cgi?id=1377049 is posted as a solution to a related problem but didn't work.

I tried eliminating the read-only tag from the OneDrive folder in Windows, but it was not enough. I tried unliking the OneDrive account from the folder, but it was not enough. As a workaround I created a new folder non-related to OneDrive and put the information there. I had previously perceived that common OneDrive folders in C:/Users are not seen in ubuntu dual boot.

**Comment by jpandre** [comment]
OneDrive is different from system compression. Its access is also triggered by a reparse point (which you should not remove, by the way).
There is some explanation which links to a plugin for accessing it from ntfs-3g in :
http://jp-andre.pagesperso-orange.fr/junctions.html#other
Also a report on its use on Ubuntu in :
https://bugs.launchpad.net/ubuntu/+source/ntfs-3g/+bug/1728354

**Comment by ebiggers** [comment]
Closing since this was not about NTFS system compression.

**Comment by Ana06** [comment]
In case it is useful to someone else, I tried to use this project to read a OneDrive folder. It didn't work, but I found something else that did work.The section Other Types of Reparse Points in the page [https://jp-andre.pagesperso-orange.fr/junctions.html](https://jp-andre.pagesperso-orange.fr/junctions.html#other) shows the differences between OneDrive and NTFS compression and links to a working [ntfs3g driver + plugins](https://jp-andre.pagesperso-orange.fr/advanced-ntfs-3g.html#download).
